insert into estoque values (default, 'Açúcar confeiteiro (g)', '', 500, 0);
insert into estoque values (default, 'Açúcar cristal (g)', '', 1000, 0);
insert into estoque values (default, 'Açúcar gelado (g)', '', 500, 0);
insert into estoque values (default, 'Açúcar mascavo (g)', '', 5000, 0);
insert into estoque values (default, 'Açúcar refinado (g)', '', 20000, 0);
insert into estoque values (default, 'Amendoim triturado (g)', '', 1000, 0);
insert into estoque values (default, 'Amido de milho (g)', '', 5000, 0);
insert into estoque values (default, 'Aveia em flocos finos (g)', '', 1000, 0);
insert into estoque values (default, 'Bicarbonato de sódio (g)', '', 500, 0);
insert into estoque values (default, 'Biscoito Oreo (g)', '', 180, 0);
insert into estoque values (default, 'Cacau em pó 100% (g)', '', 20000, 0);
insert into estoque values (default, 'Canela em pó 100% (g)', '', 500, 0);
insert into estoque values (default, 'Canudinho de waffer (g)', '', 500, 0);
insert into estoque values (default, 'Casquinha de waffer - cone (g)', '', 500, 0);
insert into estoque values (default, 'Chantilly (mL)', '', 14000, 0);
insert into estoque values (default, 'Chocolate ao leite em barra (g)', '', 10000, 0);
insert into estoque values (default, 'Chocolate branco em barra (g)', '', 4000, 0);
insert into estoque values (default, 'Chocolate fracionado branco (g)', '', 2000, 0);
insert into estoque values (default, 'Chocolate fracionado meio amargo (g)', '', 4000, 0);
insert into estoque values (default, 'Chocolate Kit Kat (g)', '', 830, 0);
insert into estoque values (default, 'Chocolate meio amargo em barra (g)', '', 10000, 0);
insert into estoque values (default, 'Coco ralado queimado (g)', '', 1000, 0);
insert into estoque values (default, 'Coco ralado seco (g)', '', 5000, 0);
insert into estoque values (default, 'Conhaque Dreher (mL)', '', 1000, 0);
insert into estoque values (default, 'Corante em gel amarelo (g)', '', 15, 0);
insert into estoque values (default, 'Corante em gel azul (g)', '', 15, 0);
insert into estoque values (default, 'Corante em gel laranja (g)', '', 15, 0);
insert into estoque values (default, 'Corante em gel lilás (g)', '', 15, 0);
insert into estoque values (default, 'Corante em gel preto (g)', '', 15, 0);
insert into estoque values (default, 'Corante em gel rosa (g)', '', 15, 0);
insert into estoque values (default, 'Corante em gel verde (g)', '', 15, 0);
insert into estoque values (default, 'Corante em gel vermelho (g)', '', 15, 0);
insert into estoque values (default, 'Corante para chocolate amarelo (g)', '', 15, 0);
insert into estoque values (default, 'Corante para chocolate azul (g)', '', 15, 0);
insert into estoque values (default, 'Corante para chocolate preto (g)', '', 15, 0);
insert into estoque values (default, 'Corante para chocolate rosa (g)', '', 15, 0);
insert into estoque values (default, 'Corante para chocolate verde (g)', '', 15, 0);
insert into estoque values (default, 'Corante para chocolate vermelho (g)', '', 15, 0);
insert into estoque values (default, 'Cravo em pó (g)', '', 300, 0);
insert into estoque values (default, 'Creme de avelã - Nutella (g)', '', 650, 0);
insert into estoque values (default, 'Creme de leite (g)', '', 10000, 0);
insert into estoque values (default, 'Doce de leite (g)', '', 10000, 0);
insert into estoque values (default, 'Emulsificante (g)', '', 1000, 0);
insert into estoque values (default, 'Essência de banana (mL)', '', 30, 0);
insert into estoque values (default, 'Essência de baunilha (mL)', '', 1000, 0);
insert into estoque values (default, 'Essência de laranja (mL)', '', 30, 0);
insert into estoque values (default, 'Essência de limão (mL)', '', 30, 0);
insert into estoque values (default, 'Essência de mel (mL)', '', 1000, 0);
insert into estoque values (default, 'Essência de rum (mL)', '', 1000, 0);
insert into estoque values (default, 'Farinha de amendoim (g)', '', 500, 0);
insert into estoque values (default, 'Farinha de trigo (g)', '', 15000, 0);
insert into estoque values (default, 'Fermento químico em pó (g)', '', 2000, 0);
insert into estoque values (default, 'Flocos de coco (g)', '', 5000, 0);
insert into estoque values (default, 'Fubá mimoso (g)', '', 1000, 0);
insert into estoque values (default, 'Gelatina incolor (g)', '', 300, 0);
insert into estoque values (default, 'Granulado chocolate (g)', '', 5000, 0);
insert into estoque values (default, 'Granulado colorido (g)', '', 2000, 0);
insert into estoque values (default, 'Leite condensado (g)', '', 43000, 0);
insert into estoque values (default, 'Leite em pó (g)', '', 10000, 0);
insert into estoque values (default, 'Leite integral (mL)', '', 10000, 0);
insert into estoque values (default, 'Manteiga (g)', '', 500, 0);
insert into estoque values (default, 'Mel (mL)', '', 2000, 0);
insert into estoque values (default, 'Milho de pipoca (g)', '', 1500, 0);
insert into estoque values (default, 'Noz moscada em pó (g)', '', 300, 0);
insert into estoque values (default, 'Óleo de soja (mL)', '', 2000, 0);
insert into estoque values (default, 'Ovos (g)', '', 10000, 0);
insert into estoque values (default, 'Paçoca de rolha (g)', '', 800, 0);
insert into estoque values (default, 'Pasta americana branca (g)', '', 3000, 0);
insert into estoque values (default, 'Pó brilhante para decoração dourado (g)', '', 20, 0);
insert into estoque values (default, 'Pó brilhante para decoração perolado (g)', '', 20, 0);
insert into estoque values (default, 'Pó brilhante para decoração rose gold (g)', '', 20, 0);
insert into estoque values (default, 'Pó brilhante para decoração vermelho (g)', '', 20, 0);
insert into estoque values (default, 'Sal (g)', '', 1000, 0);
insert into estoque values (default, '', 'Bandeja de isopor', 0, 100);
insert into estoque values (default, '', 'Caixa de papelão viagem 100 unidades', 0, 50);
insert into estoque values (default, '', 'Caixa de papelão viagem 50 unidades', 0, 25);
insert into estoque values (default, '', 'Embalagem de acetato para bolo 35MA', 0, 10);
insert into estoque values (default, '', 'Embalagem de acetato para bolo 50MA', 0, 100);
insert into estoque values (default, '', 'Embalagem de acetato para bolo 50MB', 0, 50);
insert into estoque values (default, '', 'Fôrma de docinho quatro pétalas branca', 0, 5000);
insert into estoque values (default, '', 'Fôrminha de papel N°5 para docinhos', 0, 500);
insert into estoque values (default, '', 'Fundo renda para doce', 0, 1000);
insert into estoque values (default, '', 'Placa de isopor para bolo 15 cm', 0, 25);
insert into estoque values (default, '', 'Placa de isopor para bolo 25 cm', 0, 25);
insert into estoque values (default, '', 'Placa de isopor para bolo 35 cm', 0, 25);
insert into estoque values (default, '', 'Vela mágica', 0, 50);